<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <?php
    require_once ('/amigosproanimal/pages/includes-head.phtml');
    require_once ('/amigosproanimal/pages/error-404.php');
    ?>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

<!-- Vendor CSS Files -->
<link rel="stylesheet" href="/amigosproanimal/assets/plugins/bootstrap/css/bootstrap.min.css">
<!-- <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
<!-- <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet"> -->
<!-- <link rel="stylesheet" href="/assets/css/"> -->
<!-- <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet"> -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/b96d05f45a.js" crossorigin="anonymous"></script>

<!-- Template Main CSS File -->
<link href="/amigosproanimal/assets/css/pages/header-styles.css" rel="stylesheet">
<!-- <link href="/amigosproanimal/assets/css/pages/footer-styles.css" rel="stylesheet"> -->

    <title>Amigos Pro Animal</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top header-transparent">
        <div class="container-fluid">

            <div class="row justify-content-center">
                <div class="col-xl-11 d-flex align-items-center">
                    <h1 class="logo">
                        <a href="/amigosproanimal/pages/home.phtml"> <img src="/amigosproanimal/assets/images/logo-apa-blanco.png"></a>
                    </h1>
                    <!-- Uncomment below if you prefer to use an image logo -->
                    <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

                    <nav class="nav-menu d-none d-lg-block" style="margin-left: 150px;">
                        <ul>

                            <li style="color: white;"><i class="fas fa-list-alt fa-2x"></i>
                                <h6 class="mt-3">ACCIONES</h6>
                            </li>
                            <li style="color: white;"><i class="fas fa-user-friends fa-2x"></i>
                                <h6 class="mt-3">PERSONAS</h6>
                            </li>
                            <li style="color: white;"><i class="fas fa-paw fa-2x"></i>
                                <h6 class="mt-3">MASCOTAS</h6>
                            </li>
                            <li style="color: white;"><i class="fas fa-box-open fa-2x"></i>
                                <h6 class="mt-3">INVENTARIO</h6>
                            </li>
                            <li style="color: white;"><i class="fas fa-hand-holding-usd fa-2x"></i>
                                <h6 class="mt-3">DONACIONES</h6>
                            </li>




                        </ul>
                    </nav>
                    <!-- .nav-menu -->

                    <h1 class=" right nav-menu d-none d-lg-block">
                        <ul>
                            <li class="drop-down"><i class="fas fa-user fa-2x"></i>
                                <ul>
                                    <li><a href="#">MI CUENTA</a></li>
                                    <li><a href="#">SALIR</a></li>
                                </ul>
                            </li>
                        </ul>
                    </h1>
                </div>
            </div>

        </div>
    </header>
    <!-- End Header -->

    <script src="/amigosproanimal/assets/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap tether Core JavaScript -->
    <script src="/amigosproanimal/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="/amigosproanimal/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!--Wave Effects -->
    <script src="/amigosproanimal/assets/js/waves.js"></script>
</body>

</html>