
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

<!-- Vendor CSS Files -->
<link rel="stylesheet" href="/amigosproanimal/assets/plugins/bootstrap/css/bootstrap.min.css">
<!-- <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
<!-- <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet"> -->
<!-- <link rel="stylesheet" href="/assets/css/"> -->
<!-- <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet"> -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/b96d05f45a.js" crossorigin="anonymous"></script>

<!-- Template Main CSS File -->
<link href="/amigosproanimal/assets/css/pages/header-styles.css" rel="stylesheet">
<link href="/amigosproanimal/assets/css/pages/footer-styles.css" rel="stylesheet">
